#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
usage: scripts/audit-ni-daqmx-sys-source.sh <ni-daqmx-sys-repo>

Inventories the local ni-daqmx-sys fork used by the optional NI-DAQmx backend.
The output is Markdown intended for docs/devices or validation notes. This
script records FFI source identity only; it does not prove NI-DAQmx runtime or
hardware behavior.
USAGE
}

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

repo=$1
if [[ ! -d "$repo/.git" ]]; then
  echo "ni-daqmx-sys repo does not contain .git: $repo" >&2
  exit 1
fi

require_file() {
  local path=$1
  if [[ ! -f "$path" ]]; then
    echo "missing expected ni-daqmx-sys file: $path" >&2
    exit 1
  fi
}

hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "missing sha256sum or shasum" >&2
    exit 1
  fi
}

require_file "$repo/Cargo.toml"
require_file "$repo/src/bindings.rs"
require_file "$repo/include/wrapper.h"
require_file "$repo/generate-bindings-linux.sh"
require_file "$repo/generate-bindings.ps1"
require_file "$repo/examples/generate_bindings.rs"
require_file "$repo/build.rs"

contains() {
  local path=$1
  local pattern=$2
  grep -F -- "$pattern" "$path" >/dev/null 2>&1
}

check_file_text() {
  local path=$1
  local pattern=$2
  if contains "$path" "$pattern"; then
    echo "present"
  else
    echo "missing"
  fi
}

check_status() {
  local status=$1
  if [[ "$status" == "present" ]]; then
    echo "ok"
  else
    echo "missing"
  fi
}

binding_report() {
  local label=$1
  shift
  local found=()
  local missing=()
  for symbol in "$@"; do
    if grep -E "\\b${symbol}\\b" "$repo/src/bindings.rs" >/dev/null 2>&1; then
      found+=("\`$symbol\`")
    else
      missing+=("\`$symbol\`")
    fi
  done
  local found_text="none"
  local missing_text="none"
  if [[ ${#found[@]} -gt 0 ]]; then
    found_text=${found[0]}
    for item in "${found[@]:1}"; do
      found_text+=", $item"
    done
  fi
  if [[ ${#missing[@]} -gt 0 ]]; then
    missing_text=${missing[0]}
    for item in "${missing[@]:1}"; do
      missing_text+=", $item"
    done
  fi
  echo "| $label | $found_text | $missing_text |"
}

revision=$(git -C "$repo" rev-parse HEAD)
status=$(git -C "$repo" status --short)
version=$(awk -F '"' '/^version = / { print $2; exit }' "$repo/Cargo.toml")
edition=$(awk -F '"' '/^edition = / { print $2; exit }' "$repo/Cargo.toml")
license=$(awk -F '"' '/^license = / { print $2; exit }' "$repo/Cargo.toml")
bindgen_dependency=$(awk -F '"' '/^bindgen = / { print $2; exit }' "$repo/Cargo.toml")
generated_bindgen_version=$(awk '
  /automatically generated by rust-bindgen/ {
    gsub(/\*\//, "")
    print $6
    exit
  }
' "$repo/src/bindings.rs")
windows_library_path=$(check_file_text "$repo/build.rs" 'National Instruments\Shared\ExternalCompilerSupport\C\')
linux_library_path=$(check_file_text "$repo/build.rs" '/usr/lib/x86_64-linux-gnu/')
macos_unsupported_guard=$(check_file_text "$repo/build.rs" 'target_os = "macos"')
linux_specific_cfg=$(check_file_text "$repo/build.rs" 'target_os = "linux"')
non_windows_32_bit_guard=$(check_file_text "$repo/build.rs" 'nidaqmx-sys only compiles for 64 bit Unix OSes')
unsupported_other_guard=$(check_file_text "$repo/build.rs" 'only supports Windows and audited Linux targets')

echo "# NI-DAQmx Sys Source Inventory"
echo
echo "| Item | Value |"
echo "| --- | --- |"
echo "| Source repo | \`$repo\` |"
echo "| Package version | \`$version\` |"
echo "| Package edition | \`${edition:-unknown}\` |"
echo "| Package license | \`${license:-unknown}\` |"
echo "| Cargo bindgen dependency | \`${bindgen_dependency:-unknown}\` |"
echo "| Generated bindgen version | \`${generated_bindgen_version:-unknown}\` |"
echo "| Git revision | \`$revision\` |"
if [[ -z "$status" ]]; then
  echo "| Worktree status | clean |"
else
  echo "| Worktree status | dirty |"
fi
echo "| Generated bindings SHA-256 | \`$(hash_file "$repo/src/bindings.rs")\` |"
echo "| Bindgen wrapper SHA-256 | \`$(hash_file "$repo/include/wrapper.h")\` |"
echo "| Linux bindgen script SHA-256 | \`$(hash_file "$repo/generate-bindings-linux.sh")\` |"
echo "| Windows bindgen script SHA-256 | \`$(hash_file "$repo/generate-bindings.ps1")\` |"
echo "| Cargo bindgen fallback SHA-256 | \`$(hash_file "$repo/examples/generate_bindings.rs")\` |"
echo "| Build script SHA-256 | \`$(hash_file "$repo/build.rs")\` |"
echo
echo "## Platform And Bindgen Inputs"
echo
echo "| Check | Status |"
echo "| --- | --- |"
echo "| Cargo links nidaqmx | $(check_file_text "$repo/Cargo.toml" 'links = "nidaqmx"') |"
echo "| build.rs links nidaqmx | $(check_file_text "$repo/build.rs" 'cargo:rustc-link-lib=nidaqmx') |"
echo "| build.rs has Windows library path | $windows_library_path |"
echo "| build.rs has Linux x86_64 library path | $linux_library_path |"
echo "| build.rs has explicit macOS unsupported guard | $macos_unsupported_guard |"
echo "| build.rs has Linux-specific non-Windows cfg | $linux_specific_cfg |"
echo "| build.rs rejects 32-bit non-Windows | $non_windows_32_bit_guard |"
echo "| build.rs rejects unsupported non-Linux/non-Windows targets | $unsupported_other_guard |"
echo "| wrapper includes NIDAQmx.h | $(check_file_text "$repo/include/wrapper.h" 'NIDAQmx.h') |"
echo "| Linux bindgen script reads NIDAQMX_INCLUDE_DIR | $(check_file_text "$repo/generate-bindings-linux.sh" 'NIDAQMX_INCLUDE_DIR') |"
echo "| Linux bindgen script allowlists DAQmx symbols | $(check_file_text "$repo/generate-bindings-linux.sh" '--allowlist-function "$allow_pattern"') |"
echo "| Windows bindgen script uses NI ExternalCompilerSupport include path | $(check_file_text "$repo/generate-bindings.ps1" 'ExternalCompilerSupport\C\include') |"
echo "| Windows bindgen script allowlists DAQmx symbols | $(check_file_text "$repo/generate-bindings.ps1" '--allowlist-function') |"
echo "| Linux bindgen script has Cargo fallback | $(check_file_text "$repo/generate-bindings-linux.sh" 'cargo run --example generate_bindings') |"
echo "| Windows bindgen script has Cargo fallback | $(check_file_text "$repo/generate-bindings.ps1" 'cargo run --example generate_bindings') |"
echo "| Cargo fallback reads include-dir argument | $(check_file_text "$repo/examples/generate_bindings.rs" '--include-dir') |"
echo "| Cargo fallback allowlists DAQmx symbols | $(check_file_text "$repo/examples/generate_bindings.rs" 'allowlist_function') |"
echo "| Generated bindings use signed macro constants | $(check_file_text "$repo/generate-bindings-linux.sh" '--default-macro-constant-type signed') |"
echo "| Crate root includes generated bindings | $(check_file_text "$repo/src/lib.rs" 'include!("bindings.rs")') |"
echo "| Fork contains runtime smoke test | $(check_file_text "$repo/src/lib.rs" 'fn smoke_test()') |"
echo "| Fork runtime smoke test is ignored by default | $(check_file_text "$repo/src/lib.rs" '#[ignore =') |"
echo
echo "## Platform Boundary Verdict"
echo
echo "| Boundary | Status | Notes |"
echo "| --- | --- | --- |"
echo "| Windows link path recorded | $(check_status "$windows_library_path") | Requires installed Windows header audit and Windows bindgen regeneration before publishing Windows bindings |"
echo "| Linux x86_64 link path recorded | $(check_status "$linux_library_path") | Requires installed Linux header audit and Linux bindgen regeneration matching the recorded runtime/package |"
echo "| Linux cfg is target-specific | $(check_status "$linux_specific_cfg") | The Linux library path should not apply to every non-Windows target |"
echo "| macOS explicitly unsupported | $(check_status "$macos_unsupported_guard") | macOS must remain unsupported unless a target SDK/runtime and binding audit exist |"
echo "| Other non-Linux/non-Windows targets explicitly unsupported | $(check_status "$unsupported_other_guard") | Unsupported targets must not accidentally inherit Linux linker behavior |"
echo "| 32-bit non-Windows rejected | $(check_status "$non_windows_32_bit_guard") | This is only an architecture guard; it is not an OS-support boundary |"
echo
echo "## Generated Binding Symbol Availability"
echo
echo "| Area | Found | Missing |"
echo "| --- | --- | --- |"
binding_report "Task lifecycle" DAQmxCreateTask DAQmxStartTask DAQmxStopTask DAQmxClearTask DAQmxWaitUntilTaskDone
binding_report "Analog output" DAQmxCreateAOVoltageChan DAQmxWriteAnalogF64
binding_report "Digital output" DAQmxCreateDOChan DAQmxWriteDigitalLines
binding_report "Analog input" DAQmxCreateAIVoltageChan DAQmxReadAnalogF64
binding_report "Counter input" DAQmxCreateCICountEdgesChan DAQmxReadCounterU32 DAQmxReadCounterF64
binding_report "Counter output" DAQmxCreateCOPulseChanFreq DAQmxCreateCOPulseChanTicks
binding_report "Timing and triggers" DAQmxCfgSampClkTiming DAQmxCfgImplicitTiming DAQmxCfgDigEdgeStartTrig DAQmxCfgDigEdgeRefTrig
binding_report "Errors" DAQmxGetExtendedErrorInfo DAQmxGetErrorString
binding_report "Runtime version" DAQmxGetSysNIDAQMajorVersion DAQmxGetSysNIDAQMinorVersion DAQmxGetSysNIDAQUpdateVersion DAQmx_Sys_NIDAQMajorVersion DAQmx_Sys_NIDAQMinorVersion DAQmx_Sys_NIDAQUpdateVersion
binding_report "Important aliases" TaskHandle int32 uInt32
binding_report "Constants" DAQmx_Val_Volts DAQmx_Val_FiniteSamps DAQmx_Val_Rising DAQmx_Val_ChanForAllLines DAQmx_Val_GroupByScanNumber
echo
echo "## Evidence Boundary"
echo
echo "This inventory records the local FFI source used by numanager's optional"
echo "NI-DAQmx backend. Regenerate bindings from the installed target-platform"
echo "NI header with the bindgen scripts and update these hashes when the fork changes."
echo "The scripts prefer an installed bindgen CLI and may fall back to the"
echo "fork-local Cargo generator using the same checked-in bindgen crate version."
echo "Windows support still requires running the same header audit and bindgen"
echo "script procedure against an installed Windows NI header before publishing a Windows"
echo "binding update."
echo "A complete platform boundary requires the fork build script to keep Linux"
echo "link paths under a Linux-specific cfg and to reject unsupported macOS targets"
echo "explicitly; downstream target-scoping is useful defense-in-depth but is not a"
echo "substitute for the fork recording its own support boundary."
echo "macOS support remains unsupported unless NI provides a target SDK/runtime and"
echo "the fork records a separate target-platform link and bindgen audit; a Linux"
echo "non-Windows fallback is not sufficient."
echo "The fork-local smoke test is ignored by default, is a runtime probe only,"
echo "and is not used as numanager evidence for task behavior."
echo "This is not evidence of task ordering, route validity, completion semantics,"
echo "or hardware behavior."
