#!/usr/bin/env bash
set -euo pipefail

require_path() {
  local path=$1
  local description=$2
  if [[ ! -e "$path" ]]; then
    printf 'missing %s: %s\n' "$description" "$path" >&2
    exit 1
  fi
}

require_line() {
  local file=$1
  local pattern=$2
  local description=$3
  if ! rg -F -- "$pattern" "$file" >/dev/null; then
    printf 'missing %s in %s: %s\n' "$description" "$file" "$pattern" >&2
    exit 1
  fi
}

run_audit() {
  local name=$1
  shift
  printf 'running %s\n' "$name" >&2
  "$@" >/dev/null
}

require_path crates/numanager-drivers/src/sim_sample.rs 'shared specimen model'
require_path crates/numanager-drivers/src/sim_lsm_model.rs 'confocal sampling model'
require_path crates/numanager-drivers/src/sim_lsm.rs 'LSM simulator driver'
require_path crates/numanager-drivers/src/sim_microscope_lsm.rs 'composed microscope/LSM simulator'
require_path crates/numanager-examples/src/lsm_gui.rs 'LSM GUI runtime client'
require_path crates/numanager-imswitch-daqmx/src/lib.rs 'ImSwitch DAQmx descriptor/backend'
require_path docs/devices/sim-microscope.md 'brightfield simulator documentation'
require_path docs/devices/sim-lsm.md 'sim LSM device documentation'
require_path docs/devices/sim-microscope-lsm.md 'composed simulator documentation'
require_path docs/devices/ni-daqmx-bench-validation-checklist.md 'DAQmx bench validation checklist'

require_line crates/numanager-drivers/src/lib.rs 'mod sim_sample;' 'shared specimen internal module'
require_line crates/numanager-drivers/src/lib.rs 'mod sim_lsm_model;' 'confocal sampling internal module'
require_line crates/numanager-drivers/src/lib.rs 'pub mod sim_lsm;' 'LSM simulator module export'
require_line crates/numanager-drivers/src/lib.rs 'pub mod sim_microscope_lsm;' 'composed simulator module export'
require_line crates/numanager-examples/src/main.rs 'lsm_confocal_capture' 'LSM capture example registration'
require_line crates/numanager-examples/src/main.rs 'lsm_signal_stream' 'LSM signal example registration'
require_line crates/numanager-examples/src/main.rs 'lsm_gui' 'LSM GUI example registration'
require_line crates/numanager-examples/src/main.rs 'lsm_daqmx_bringup_plan' 'DAQmx bring-up example registration'
require_line docs/run_examples.md 'scripts/audit-lsm-simulator-workflows.sh' 'LSM simulator audit documentation'
require_line docs/run_examples.md 'scripts/audit-lsm-daqmx-plan-nonhardware.sh' 'plan aggregate audit documentation'
require_line docs/run_examples.md 'scripts/audit-ni-daqmx-plan-validation.sh' 'DAQmx plan-validation audit documentation'
require_line docs/devices/README.md 'sim_microscope' 'brightfield simulator device index'
require_line docs/devices/README.md 'sim_lsm' 'LSM simulator device index'
require_line docs/devices/README.md 'sim_microscope_lsm' 'composed simulator device index'
require_line docs/devices/sim-lsm.md 'detector_gain' 'sim LSM detector gain property documentation'
require_line docs/devices/sim-lsm.md 'detector_noise' 'sim LSM detector noise property documentation'
require_line docs/example_outputs.md '# LSM/DAQmx Plan Non-Hardware Audit' 'recorded plan aggregate audit output'
require_line docs/example_outputs.md 'Scan-signal stream timing/drop metadata' 'recorded simulator signal metadata audit row'
require_line docs/example_outputs.md 'LSM GUI smoke frame/chunk metadata consumption' 'recorded simulator GUI metadata audit row'
require_line docs/example_outputs.md '# NI-DAQmx Plan Validation Audit' 'recorded DAQmx plan-validation audit output'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '--frequency 0' 'bench checklist positive frequency guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '--duty-cycle NaN' 'bench checklist finite duty-cycle guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '--simulate-setup-error-after 1' 'bench checklist plan setup cleanup simulation'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '--simulate-setup-error-after 1' 'saved plan plan setup cleanup simulation'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'AO smoke ranges that exclude the 0 V final write' 'bench checklist AO safe-zero guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'I/O smoke safe-final-state planning' 'saved plan I/O smoke safe-final-state planning'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'preflight `waveform_preview` rows' 'bench checklist waveform preview'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`waveform_preview` rows' 'saved plan waveform preview'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`raster_timing_preview` rows' 'bench checklist raster timing preview'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`raster_timing_preview` row' 'saved plan raster timing preview'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`signal_timing_preview` rows' 'bench checklist signal timing preview'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`signal_timing_preview` row' 'saved plan signal timing preview'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`planned_timing` rows' 'bench checklist task timing preview'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_timing` rows' 'saved plan task timing preview'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`planned_runtime_sequence` and `planned_completion` rows' 'bench checklist finite runtime sequence'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Preflight `planned_execution_contract` rows' 'bench checklist execution contract row'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_runtime_sequence` and' 'saved plan finite runtime sequence'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_execution_contract`' 'saved plan helper execution contract preflight rows'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_plan_setup_helper_impl.rs 'planned_publication' 'DAQmx helper publication preflight rows'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_plan_setup_helper_impl.rs 'planned_execution_contract' 'DAQmx helper execution contract preflight rows'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_plan_setup_helper_impl.rs 'planned_live_executor' 'DAQmx helper live executor preflight rows'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_plan_setup_helper_impl.rs 'planned_reconstruction' 'DAQmx helper reconstruction preflight rows'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Preflight `planned_publication` rows' 'bench checklist helper publication preflight rows'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`planned_live_executor`' 'bench checklist helper live executor preflight rows'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`planned_reconstruction`' 'bench checklist helper reconstruction preflight rows'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Runtime publication intent' 'validation-note publication intent row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Reconstruction intent' 'validation-note reconstruction intent row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Runtime capture frame publication' 'validation-note capture publication evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Runtime live frame stream publication' 'validation-note live publication evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Runtime signal chunk publication' 'validation-note signal publication evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'required_metadata={required_metadata}' 'validation-note publication required-metadata preflight targets'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Live executor' 'validation-note live executor preflight targets'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'reconstruction_expectations' 'validation-note reconstruction preflight targets'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Runtime capture frame publication' 'bench checklist capture publication evidence row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Runtime live frame stream publication' 'bench checklist live publication evidence row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Runtime signal chunk publication' 'bench checklist signal publication evidence row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Live executor intent' 'bench checklist live executor intent row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'runtime_sequence_expectations' 'validation-note runtime-sequence preflight targets'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Live readiness' 'validation-note live readiness preflight targets'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Task-plan live readiness showing per-plan blocker' 'validation-note live readiness evidence checklist row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs '"Runtime version comparison"' 'validation-note backend readiness runtime-version comparison row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs '"Runtime version comparison basis"' 'validation-note backend readiness runtime-version comparison basis row'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'pending_hardware_validation' 'saved plan hardware-validation blocker'
require_line docs/example_outputs.md 'Live-task intent with metadata and runtime probe reaches hardware-validation blocker' 'recorded runtime-probe hardware-validation blocker audit row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'LSM bring-up backend_readiness line' 'validation-note bring-up readiness artifact row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'LSM bring-up plan with backend_readiness' 'validation-note bring-up readiness evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'print_backend_inventory' 'validation-note backend inventory section'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Backend inventory readiness table' 'validation-note backend inventory artifact row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Backend inventory readiness showing helper isolation' 'validation-note backend inventory evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Bench safety preconditions table' 'validation-note bench safety artifact row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Bench safety preconditions recorded before --execute helper commands' 'validation-note bench safety evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'Task-plan readiness agreement' 'validation-note backend/task-plan readiness agreement row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'backend_status_runtime_version_and_daqmx_task_plan' 'validation-note readiness agreement includes runtime-version fields'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'print_external_promotion_gates' 'validation-note external promotion gate evidence section'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'bench_safety_preconditions' 'validation-note bench-safety promotion gate evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'task_ordering_routing_completion_cleanup_bench_validation' 'validation-note task-behavior promotion gate evidence row'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'cleanup_expectations' 'validation-note cleanup preflight targets'
require_line docs/devices/imswitch-daqmx.md '`planned_publication` rows' 'device docs helper publication preflight rows'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_publication` rows' 'saved plan helper publication preflight rows'
require_line docs/devices/imswitch-daqmx.md '`planned_live_executor` rows' 'device docs helper live executor preflight rows'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_live_executor` rows' 'saved plan helper live executor preflight rows'
require_line docs/devices/imswitch-daqmx.md '`planned_reconstruction` rows' 'device docs helper reconstruction preflight rows'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_reconstruction` rows' 'saved plan helper reconstruction preflight rows'
require_line crates/numanager-imswitch-daqmx/src/lib.rs 'reconstruction_plan' 'DAQmx public reconstruction plan metadata'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_plan_setup_helper_impl.rs 'planned_cleanup' 'DAQmx helper cleanup preflight rows'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Preflight `planned_cleanup` rows' 'bench checklist helper cleanup preflight rows'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'LSM bring-up `backend_readiness` line' 'bench checklist bring-up readiness artifact row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '`backend_readiness` line with live-task blocker, runtime-version comparison, and `promotion_gate_statuses`' 'bench checklist bring-up readiness expected evidence'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Backend inventory readiness table' 'bench checklist backend inventory artifact row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Backend inventory readiness | Generated validation-note' 'bench checklist backend inventory expected evidence'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Bench safety preconditions table' 'bench checklist safety artifact row'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Bench safety preconditions | Completed generated validation-note' 'bench checklist safety expected evidence'
require_line scripts/audit-ni-daqmx-external-gates.sh 'Bench safety preconditions remain explicit before execute helpers' 'external-gates audit safety gate output'
require_line scripts/audit-ni-daqmx-external-gates.sh '--execute --bench-safety-reviewed' 'external-gates audit acknowledged execute marker'
require_line crates/numanager-imswitch-daqmx/src/bin/daqmx_io_smoke_helper_impl.rs '--bench-safety-reviewed after completing the bench safety preconditions' 'I/O smoke execute safety acknowledgement guard'
require_line crates/numanager-examples/src/lsm_daqmx_commands.rs '--execute --bench-safety-reviewed' 'generated I/O smoke execute safety acknowledgement'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md '--execute --bench-safety-reviewed' 'bench checklist acknowledged I/O execute command'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '--execute --bench-safety-reviewed' 'saved plan acknowledged I/O execute command'
require_line docs/devices/imswitch-daqmx.md '`planned_cleanup` rows' 'device docs helper cleanup preflight rows'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`planned_cleanup` rows' 'saved plan helper cleanup preflight rows'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"runtime_sequence"' 'DAQmx task-plan runtime sequence metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"completion_plan"' 'DAQmx task-plan completion metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"execution_contract"' 'DAQmx task-plan execution contract metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"live_executor_plan"' 'DAQmx task-plan live executor metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs 'not_enabled_pending_hardware_validation' 'DAQmx live executor remains hardware-validation gated'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"contract_evidence_status"' 'DAQmx task-plan execution contract evidence status'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"live_task_execution_blocker"' 'DAQmx task-plan live execution blocker metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"live_task_execution_readiness"' 'DAQmx task-plan live readiness metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"external_promotion_gates"' 'DAQmx external promotion gate metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"external_promotion_gate_statuses"' 'DAQmx structured external promotion gate statuses'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"bench_safety_preconditions"' 'DAQmx bench-safety external promotion gate metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"publication_plan"' 'DAQmx task-plan publication metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"publication_evidence_status"' 'DAQmx publication evidence status'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"frame_handle"' 'DAQmx publication frame-handle metadata requirement'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"sample_values"' 'DAQmx publication sample-values metadata requirement'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"cancel_plan"' 'DAQmx task-plan cancel metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"cancel_evidence_status"' 'DAQmx cancel evidence status'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"failure_cleanup_modes"' 'DAQmx cleanup failure mode metadata'
require_line crates/numanager-imswitch-daqmx/src/lib.rs '"started_task_cleanup"' 'DAQmx started-task cleanup metadata'
require_line docs/devices/imswitch-daqmx.md '`runtime_sequence` records the intended finite setup' 'device docs runtime sequence metadata'
require_line docs/devices/imswitch-daqmx.md 'structured `execution_contract`' 'device docs execution contract metadata'
require_line docs/devices/imswitch-daqmx.md '`contract_evidence_status=pending_hardware_validation`' 'device docs execution contract evidence status'
require_line docs/devices/imswitch-daqmx.md '`live_task_execution_blocker` fields' 'device docs task-plan live execution blocker metadata'
require_line docs/devices/imswitch-daqmx.md 'structured `live_task_execution_readiness` fields' 'device docs task-plan live readiness metadata'
require_line docs/devices/imswitch-daqmx.md '`external_promotion_gates` lists' 'device docs external promotion gate metadata'
require_line docs/devices/imswitch-daqmx.md '`external_promotion_gate_statuses` mirrors' 'device docs structured promotion gate statuses'
require_line docs/devices/imswitch-daqmx.md '`daqmx_task_plan.live_task_execution_readiness`' 'device docs mirrored task-plan gate statuses'
require_line docs/devices/imswitch-daqmx.md 'expands `external_promotion_gates` into per-gate evidence rows' 'device docs validation-note external promotion gates'
require_line docs/devices/imswitch-daqmx.md '`lsm_gui imswitch` source summary' 'device docs GUI promotion gate summary'
require_line docs/devices/imswitch-daqmx.md 'A structured `publication_plan`' 'device docs publication plan metadata'
require_line docs/devices/imswitch-daqmx.md 'structured `cancel_plan`' 'device docs cancel plan metadata'
require_line docs/devices/imswitch-daqmx.md 'expected failure-cleanup modes' 'device docs cleanup failure mode metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'structured `runtime_sequence` and `completion_plan` metadata' 'saved plan runtime sequence metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'structured `execution_contract` metadata' 'saved plan execution contract metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`live_task_execution_blocker`' 'saved plan task-plan live execution blocker metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`live_task_execution_readiness`' 'saved plan task-plan live readiness metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`external_promotion_gates`' 'saved plan external promotion gate metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`external_promotion_gate_statuses`' 'saved plan structured promotion gate statuses'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'mirrored into `daqmx_task_plan.live_task_execution_readiness`' 'saved plan mirrored task-plan gate statuses'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'per-gate evidence rows' 'saved plan validation-note external promotion gates'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'bench safety preconditions, runtime' 'saved plan external-gates audit safety gate'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`promotion_gate_statuses=[pending=9]`' 'saved plan GUI promotion gate summary'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`backend_readiness`' 'saved plan bring-up backend readiness summary'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'explicit artifact/evidence row' 'saved plan bring-up readiness checklist artifact'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`Backend Inventory` table' 'saved plan backend inventory validation-note section'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`publication_plan`' 'saved plan publication plan metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`sample_values`' 'saved plan canonical signal publication metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'split runtime-publication evidence rows' 'saved plan split runtime publication evidence'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md '`cancel_plan`' 'saved plan cancel plan metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'failure-cleanup modes' 'saved plan cleanup failure mode metadata'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'preflight evidence targets' 'saved plan validation-note preflight target summaries'
require_line crates/numanager-examples/src/daqmx_runtime_probe.rs 'promotion_gates:' 'runtime-probe promotion gate summary output'
require_line crates/numanager-examples/src/daqmx_runtime_probe.rs 'promotion_gate_statuses:' 'runtime-probe promotion gate status summary output'
require_line crates/numanager-examples/src/daqmx_runtime_probe.rs 'inventory:' 'runtime-probe inventory summary output'
require_line crates/numanager-examples/src/lsm_daqmx_bringup_plan.rs 'backend_readiness:' 'bring-up backend readiness summary output'
require_line crates/numanager-examples/src/lsm_daqmx_bringup_plan.rs 'runtime_version_comparison_summary' 'bring-up backend readiness runtime-version summary output'
require_line crates/numanager-examples/src/lsm_daqmx_bringup_plan.rs 'promotion_gate_statuses=[' 'bring-up promotion gate status summary output'
require_line crates/numanager-examples/src/lsm_gui.rs 'promotion_gate_statuses=[' 'GUI promotion gate status summary output'
require_line docs/run_examples.md 'compact backend readiness' 'run docs bring-up backend readiness summary'
require_line docs/run_examples.md '`inventory:` summary' 'run docs runtime-probe inventory summary'
require_line docs/devices/imswitch-daqmx.md 'compact backend-readiness and promotion-gate status output' 'device docs bring-up backend readiness summary'
require_line docs/devices/imswitch-daqmx.md '`inventory:` summary' 'device docs runtime-probe inventory summary'
require_line docs/example_outputs.md 'backend_readiness: execution=not_live_backend' 'recorded bring-up backend readiness summary output'
require_line docs/example_outputs.md 'inventory: requested=true, helper=true' 'recorded inventory-request summary output'
require_line docs/example_outputs.md 'promotion_gate_statuses=[pending=9]' 'recorded GUI promotion gate status summary output'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'Derived sample-clock source' 'bench checklist derived sample-clock source'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'derived counter-output sample-clock routes' 'saved plan derived sample-clock source'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "--sample-clock-source ''" 'bench checklist empty sample-clock source guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "--start-trigger ''" 'bench checklist empty start-trigger guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "--ci ''" 'bench checklist empty physical channel guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "--ci-task ''" 'bench checklist empty task-label guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'duplicate physical channels' 'bench checklist duplicate physical-channel guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'duplicate active task labels' 'bench checklist duplicate task-label guard'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'non-finite/out-of-range duty cycle' 'validation-note duty-cycle guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'empty route sources' 'validation-note route guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'whitespace-padded route sources' 'validation-note route whitespace guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'empty channels/task labels' 'validation-note empty channel/task-label guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'duplicate physical channels' 'validation-note duplicate physical-channel guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'duplicate active task labels' 'validation-note duplicate task-label guard wording'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "numanager-daqmx-channel-setup-helper --kind co --channel '' --dry-run" 'bench checklist channel-setup empty channel guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "numanager-daqmx-io-smoke-helper --kind co --channel '' --samples 1" 'bench checklist I/O empty channel guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'single-channel helper empty channel inputs' 'saved plan single-channel empty guard'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'single-channel empty channel inputs' 'validation-note single-channel empty guard wording'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md "--name ''" 'bench checklist empty task-name guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'empty explicit task names' 'saved plan empty task-name guard'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'empty explicit task names' 'validation-note empty task-name guard wording'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'incomplete raster dimensions' 'bench checklist incomplete raster guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'raster dimension overflow' 'bench checklist raster overflow guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'raster frame-product overflow' 'bench checklist raster frame-product overflow guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'leading/trailing whitespace' 'bench checklist identifier whitespace guard'
require_line docs/devices/ni-daqmx-bench-validation-checklist.md 'whitespace-padded route sources' 'bench checklist route whitespace guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'incomplete raster dimensions' 'saved plan incomplete raster guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'raster dimension overflow' 'saved plan raster overflow guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'raster frame-product overflow' 'saved plan raster frame-product overflow guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'leading/trailing whitespace' 'saved plan identifier whitespace guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'whitespace-padded route-source inputs' 'saved plan route whitespace guard'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'incomplete raster dimensions' 'validation-note incomplete raster guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'raster dimension overflow' 'validation-note raster overflow guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'raster frame-product overflow' 'validation-note raster frame-product overflow guard wording'
require_line crates/numanager-examples/src/lsm_daqmx_validation_note.rs 'leading/trailing whitespace' 'validation-note identifier whitespace guard wording'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'Current non-hardware plan gate:' 'saved plan aggregate gate summary'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'Passing this aggregate audit means the simulator/API/documentation and' 'saved plan aggregate gate boundary'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'detector_gain' 'saved plan detector gain status'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'detector_noise' 'saved plan detector noise status'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'task execution awaiting hardware validation' 'NI-DAQmx live execution boundary'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'duplicate physical channels' 'saved plan duplicate physical-channel guard'
require_line docs/planning/lsm-simulation-and-daqmx-plan.md 'duplicate active task labels' 'saved plan duplicate task-label guard'

run_audit lsm_simulator scripts/audit-lsm-simulator-workflows.sh
run_audit reverse_evidence_boundary scripts/audit-reverse-evidence-boundary.sh
run_audit daqmx_evidence_inputs scripts/audit-ni-daqmx-evidence-inputs.sh
run_audit daqmx_external_gates scripts/audit-ni-daqmx-external-gates.sh
run_audit daqmx_target_scope scripts/audit-ni-daqmx-target-scope.sh
run_audit daqmx_no_hardware_helpers scripts/audit-ni-daqmx-no-hardware-helpers.sh
run_audit daqmx_plan_validation scripts/audit-ni-daqmx-plan-validation.sh
run_audit daqmx_live_gate scripts/audit-ni-daqmx-live-gate.sh
run_audit daqmx_runtime_probe scripts/audit-ni-daqmx-runtime-probe.sh
run_audit daqmx_example_output_sync scripts/audit-ni-daqmx-example-output-sync.sh

printf '# LSM/DAQmx Plan Non-Hardware Audit\n\n'
printf '| Boundary | Status |\n'
printf '| --- | --- |\n'
printf '| Shared specimen, simulator drivers, GUI source, and simulator docs exist | ok |\n'
printf '| Public LSM examples and DAQmx bring-up examples are registered | ok |\n'
printf '| Simulator workflow audit passes | ok |\n'
printf '| Repository reverse-evidence boundary audit passes | ok |\n'
printf '| DAQmx evidence-input, external-gates, target-scope, helper, plan-validation, live-gate, runtime-probe, and docs-sync audits pass | ok |\n'
printf '| Saved plan records live NI-DAQmx task execution as awaiting hardware validation | ok |\n'
printf '\nThis aggregate audit checks the implemented non-hardware LSM simulator workflow and DAQmx safety/documentation gates from `docs/planning/lsm-simulation-and-daqmx-plan.md`. It does not create NI-DAQmx tasks, write outputs, read inputs, execute scans on hardware, or provide hardware validation evidence.\n'
